import { AppState } from './types';

export const DEFAULT_STATE: AppState = {
  lastReset: new Date().toDateString(),
  settings: {
    parentPin: '1234',
    pointsPerMinute: 3,
    maxDailyScreenMinutes: 120,
  },
  kids: [
    {
      id: 'itai',
      name: 'איתי',
      age: 9,
      grade: "כיתה ד'",
      emoji: '⚽',
      color: '#3B82F6',
      secondaryColor: '#EFF6FF',
      interests: ['כדורגל', 'משחקים', 'ספורט'],
      totalPoints: 0,
      allTimePoints: 0,
      screenTimeEarned: 0,
      screenTimeUsed: 0,
      streak: 0,
      achievements: [],
      completedExercises: [],
      history: [],
      tasks: [
        { id: 'itai-t1', title: 'שיעורי בית מתמטיקה', points: 20, type: 'homework', completed: false, createdAt: new Date().toISOString() },
        { id: 'itai-t2', title: 'קריאת ספר - 20 דקות', points: 15, type: 'homework', completed: false, createdAt: new Date().toISOString() },
        { id: 'itai-t3', title: 'שיעורי בית עברית', points: 20, type: 'homework', completed: false, createdAt: new Date().toISOString() },
        { id: 'itai-t4', title: 'אתגר כדורגל: 50 בעיטות', points: 25, type: 'challenge', completed: false, createdAt: new Date().toISOString() },
        { id: 'itai-t5', title: 'לימוד לוח הכפל עד 9', points: 30, type: 'challenge', completed: false, createdAt: new Date().toISOString() },
        { id: 'itai-t6', title: 'עזרה בסידור הבית', points: 10, type: 'challenge', completed: false, createdAt: new Date().toISOString() },
      ],
    },
    {
      id: 'aviv',
      name: 'אביב',
      age: 6,
      grade: "כיתה א'",
      emoji: '🌸',
      color: '#EC4899',
      secondaryColor: '#FDF2F8',
      interests: ['ציור', 'שירה', 'ריקוד'],
      totalPoints: 0,
      allTimePoints: 0,
      screenTimeEarned: 0,
      screenTimeUsed: 0,
      streak: 0,
      achievements: [],
      completedExercises: [],
      history: [],
      tasks: [
        { id: 'aviv-t1', title: 'תרגול קריאה בעברית', points: 15, type: 'homework', completed: false, createdAt: new Date().toISOString() },
        { id: 'aviv-t2', title: 'שיעורי בית כתיבה', points: 20, type: 'homework', completed: false, createdAt: new Date().toISOString() },
        { id: 'aviv-t3', title: 'תרגול ספירה עד 20', points: 10, type: 'homework', completed: false, createdAt: new Date().toISOString() },
        { id: 'aviv-t4', title: 'ציור יצירתי חופשי', points: 10, type: 'challenge', completed: false, createdAt: new Date().toISOString() },
        { id: 'aviv-t5', title: 'עזרה בסידור הצעצועים', points: 10, type: 'challenge', completed: false, createdAt: new Date().toISOString() },
        { id: 'aviv-t6', title: 'שיר בעל פה חדש', points: 15, type: 'challenge', completed: false, createdAt: new Date().toISOString() },
      ],
    },
  ],
};
